### ISSUE TITLE
NullPointerException - `mListener` is null when trying to deliver error

### ISSUE THREAD

**Issue by projectdelta6** [globalpayments/rxp-android#25]
Here is the Log from Sentry:
```
java.lang.NullPointerException: Attempt to invoke interface method 'void com.realexpayments.hpp.HPPManagerListener.hppManagerFailedWithError(com.realexpayments.hpp.HPPError)' on a null object reference
    at com.realexpayments.hpp.HPPManagerFragment$3.onReceivedError(HPPManagerFragment.java:251)
    at Uy0.c(chromium-TrichromeWebViewGoogle.aab-stable-495106133:160)
    at P9.handleMessage(chromium-TrichromeWebViewGoogle.aab-stable-495106133:521)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:236)
    at android.app.ActivityThread.main(ActivityThread.java:8043)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
```

**Comment by jhonjtabareso** [comment]
> 

@projectdelta6 Hello, one fast question, are you trying to do some operation with external storage or files?

**Comment by projectdelta6** [comment]
@jhonjtabareso No, not as far as I'm aware

**Comment by jhonjtabareso** [comment]
> @jhonjtabareso No, not as far as I'm aware

Ok, so in the HppManager inside MainActivity, you set all the params por hppmanager, without empty values?

**Comment by projectdelta6** [comment]
yes
